- name:  Get passwords
  hosts: compute
  remote_user: "jibin"
  tasks:
  
    - fail: msg="This play requires vault_token use --extra  --extra-vars 'vault_token=<token>'" 
      when: vault_token is not defined

 
    - name: Retrieving NEUTRON db pass  from vault

      set_fact: NEUTRON_DBPASS="{{ lookup('hashi_vault', 'secret=kv/openstack-deploy/NEUTRON_DBPASS:value auth_method=token token={{vault_token}} url=https://192.168.9.1:8200') }}"

    - name: Retrieving NEUTRON user pass  from vault

      set_fact: NEUTRON_PASS="{{ lookup('hashi_vault', 'secret=kv/openstack-deploy/NEUTRON_PASS:value auth_method=token token={{vault_token}} url=https://192.168.9.1:8200') }}"
    
   
    - name: Retrieving RABBIT_PASS  user pass  from vault

      set_fact: RABBIT_PASS="{{ lookup('hashi_vault', 'secret=kv/openstack-deploy/RABBIT_PASS:value auth_method=token token={{vault_token}} url=https://192.168.9.1:8200') }}"

    - name: Retrieving nova user pass  from vault

      set_fact: NOVA_PASS="{{ lookup('hashi_vault', 'secret=kv/openstack-deploy/NOVA_PASS:value auth_method=token token={{vault_token}} url=https://192.168.9.1:8200') }}"



- name: Install and configure compute node
  hosts: compute
  remote_user: "jibin"
  become: true 
  tasks: 
    - name: Install the components
      apt:
        name: 
          - neutron-linuxbridge-agent
        state: present 

    - name: Configure the server component on   /etc/neutron/neutron.conf
      template:
        src: "{{ playbook_dir }}/configs/templates/neutron_compute.conf.j2"
        dest: "/etc/neutron/neutron.conf"
        
        mode: '0640'     
    #https://docs.openstack.org/neutron/victoria/install/compute-install-option2-ubuntu.html#configure-the-linux-bridge-agent
    - name: Networking Option 2 Self-service networks - Configure the Linux bridge agent
      copy:
        src: "{{ playbook_dir }}/configs/linuxbridge_agent_compute.ini"
        dest: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini"
        
        mode: '0640'


        
- name: Finalize installation

  hosts: compute
  remote_user: "jibin"
  become: true 
  tasks:  
    - name: Restart the nova-compute  and neutron-linuxbridge-agent service
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: "{{item}}"
      with_items:
        - nova-compute 
        - neutron-linuxbridge-agent
 