

- name: Install openstack dashboard
  hosts: controller
  remote_user: "jibin"
  become: true 
  tasks: 
    - name: Install horizon
      apt:
        name: 
          - openstack-dashboard
        state: present 


    - name: Edit the /etc/openstack-dashboard/local_settings.py file
      copy:
        src: "{{ playbook_dir }}/configs/local_settings.py"
        dest: "/etc/openstack-dashboard/local_settings.py"
        
        mode: '0640'
    - name: Reload the web server configuration
      systemd:
        state: reloaded
        enabled: yes
        daemon_reload: yes
        name: "{{item}}"
      with_items:
        - apache2