- name:  Get passwords
  hosts: controller
  remote_user: "jibin"
  tasks:
  
    - fail: msg="This play requires vault_token use --extra  --extra-vars 'vault_token=<token>'" 
      when: vault_token is not defined

 
    - name: Retrieving NEUTRON db pass  from vault

      set_fact: NEUTRON_DBPASS="{{ lookup('hashi_vault', 'secret=kv/openstack-deploy/NEUTRON_DBPASS:value auth_method=token token={{vault_token}} url=https://192.168.9.1:8200') }}"

    - name: Retrieving NEUTRON user pass  from vault

      set_fact: NEUTRON_PASS="{{ lookup('hashi_vault', 'secret=kv/openstack-deploy/NEUTRON_PASS:value auth_method=token token={{vault_token}} url=https://192.168.9.1:8200') }}"
    
   
    - name: Retrieving RABBIT_PASS  user pass  from vault

      set_fact: RABBIT_PASS="{{ lookup('hashi_vault', 'secret=kv/openstack-deploy/RABBIT_PASS:value auth_method=token token={{vault_token}} url=https://192.168.9.1:8200') }}"

    - name: Retrieving nova user pass  from vault

      set_fact: NOVA_PASS="{{ lookup('hashi_vault', 'secret=kv/openstack-deploy/NOVA_PASS:value auth_method=token token={{vault_token}} url=https://192.168.9.1:8200') }}"



####  Networking Option 2: Self-service networks
# https://docs.openstack.org/neutron/victoria/install/controller-install-option2-ubuntu.html
  

- name: Install and configure self-serrvice network components
  hosts: controller
  remote_user: "jibin"
  become: true 
  tasks: 
    - name: Install self service packages
      apt:
        name: 
          - neutron-server
          - neutron-plugin-ml2
          - neutron-linuxbridge-agent
          - neutron-l3-agent
          - neutron-dhcp-agent
          - neutron-metadata-agent
        state: present 
      
    - name: Configure the server component on   /etc/neutron/neutron.conf
      template:
        src: "{{ playbook_dir }}/configs/templates/neutron.conf.j2"
        dest: "/etc/neutron/neutron.conf"
        
        mode: '0640'


    - name: Configure the Modular Layer 2 (ML2) plug-in
      copy:
        src: "{{ playbook_dir }}/configs/ml2_conf.ini"
        dest: "/etc/neutron/plugins/ml2/ml2_conf.ini"
        
        mode: '0640'

    - name: Configure the Linux bridge agent
      copy:
        src: "{{ playbook_dir }}/configs/linuxbridge_agent.ini"
        dest: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini"
        
        mode: '0640'

    - name: Check if kernel module br_netfilter is loaded  
      shell:  lsmod | grep br_netfilter

    - name: Configure the layer-3 agent
      copy:
        src: "{{ playbook_dir }}/configs/l3_agent.ini"
        dest: "/etc/neutron/l3_agent.ini"
        

        mode: '0640'
    - name: Configure the DHCP agent
      copy:
        src: "{{ playbook_dir }}/configs/dhcp_agent.ini"
        dest: "/etc/neutron/dhcp_agent.ini"
        
        mode: '0640'




- name: Finalize installation

  hosts: controller
  remote_user: "jibin"
  become: true 
  tasks: 
    - name: Populate the database
      shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
      register: out 
    
    - debug:  msg="{{out.stdout}}"

    - name: Restart the Compute services
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: "{{item}}"
      with_items:
        - nova-api
        - neutron-server 
        - neutron-linuxbridge-agent
        - neutron-dhcp-agent
        - neutron-metadata-agent
        - neutron-l3-agent

 