 
 

network:
  version: 2
        
  ethernets:
   
    veth0-openstack:
      addresses:  
        - 192.168.10.1/24 
      dhcp4: false
      optional: true
      nameservers:
        addresses: [10.0.0.11,8.8.8.8,8.8.4.4]
        search: [openstack.lab]
      # routes:
      #   # route to openstack computes
      #   - to: 192.168.10.0/24
      #     via: 192.168.9.1
 
    veth1-ovs:
      addresses:  
        - 192.168.11.1/24 
      dhcp4: false
      optional: true
      nameservers:
        addresses: [10.0.0.11,8.8.8.8,8.8.4.4]
        search: [openstack.lab]
      # routes:
      #   # route to openstack computes
      #   - to: 192.168.10.1/24
      #     via: 192.168.9.1                 
     
    