 
 

network:
  version: 2
        
 
  bridges:
    ovs0:
      routes:
        # route to openstack computes
        - to: 192.168.10.1/24
          via: 192.168.9.1
                      
     
    