
network:
  renderer: networkd

  ethernets:
   
    eno1:
      addresses:  
        - 10.0.0.31/24 # compute ip, this setup will have compute ip too
      dhcp4: true
      nameservers: 
        addresses: [8.8.8.8]
    
  version: 2

