---
# tasks file for dns

  - name: Install bind9  and tools
    apt:
      name: 
        - bind9 
        - bind9utils
        - bind9-doc
      state: present 

  - name: Create zone directory
    file:
      path: /etc/bind/zones
      state: directory
      owner: bind
      group: bind
      mode: '0750'

  - name: Copy configuration
    copy:
      src: "{{playbook_dir}}/configs/dns/{{item.src}}"  
      dest: "{{item.dest}}"
      owner: bind
      group: bind
      mode: '0600' 
    with_items:
      - { src: "named.conf.options", dest: "/etc/bind/named.conf.options" } 
      - { src: "named.conf.local", dest: "/etc/bind/named.conf.local" }
      - { src: "db.openstack.lab", dest: "/etc/bind/zones/db.openstack.lab" }
      - { src: "db.10.0", dest: "/etc/bind/zones/db.10.0" }


  - name: Check bind config 
    command: named-checkconf
  
  - name: check openstack.lab zone 
    command: named-checkzone  openstack.lab /etc/bind/zones/db.openstack.lab

  - name: check reverse lookup
    command: named-checkzone   0.10.in-addr.arpa /etc/bind/zones/db.10.0 
    notify: restart_bind

 