
## note the verification steps are incomplete 
# For more details https://docs.openstack.org/nova/victoria/install/verify.html
- name:  Get passwords
  hosts: controller
  remote_user: "jibin"
  become: true
  tasks:
  
    - fail: msg="This play requires vault_token use --extra  --extra-vars 'vault_token=<token>'" 
      when: vault_token is not defined

    - include_vars:  dir=vars 
 
    - name: Retrieving secrets  from vault
      uri:
        url: "{{vault_addr}}{{item}}"
        method: GET
        headers:
          X-Vault-Token: "{{vault_token}}"

      with_items: 
        - /v1/kv/openstack-deploy/KEYSTONE_ADMIN_PASS   

      register: output

    - name: Set ppasswords as facts 
      set_fact:  
        KEYSTONE_ADMIN_PASS:   "{{output.results[0].json.data.value}}"    

        
- name: Verify
  hosts: controller
  remote_user: "jibin"
  become: true 
  vars:
    os_env:
      OS_USERNAME: admin
      OS_PASSWORD: "{{KEYSTONE_ADMIN_PASS}}"
      OS_PROJECT_NAME: admin
      OS_USER_DOMAIN_NAME: Default
      OS_PROJECT_DOMAIN_NAME: Default
      OS_AUTH_URL: http://controller:5000/v3
      OS_IDENTITY_API_VERSION: 3
  tasks: 
    - name:  confirm there are compute hosts in the database 
      command: openstack compute service list --service nova-compute
      register: out
      environment: "{{ os_env }}"
    - debug:  msg="{{out}}"

    - name:  Discover compute hosts
      command: su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
      register: out
      environment: "{{ os_env }}"
      
    - debug:  msg="{{out}}" 
    - name:  List service components to verify successful launch and registration of each process
      command: openstack compute service list
      register: out
      environment: "{{ os_env }}"
    - debug:  msg="{{out}}"



    - name: List API endpoints in the Identity service to verify connectivity with the Identity service
      command: openstack catalog list
      register: out
      environment: "{{ os_env }}"
    - debug:  msg="{{out}}"

    - name: List images in the Image service to verify connectivity with the Image service
      command: openstack image list
      register: out
      environment: "{{ os_env }}"
    - debug:  msg="{{out}}"

    - name: Check the cells and placement API are working successfully and that other necessary prerequisites are in place
      command: nova-status upgrade check
      register: out
      environment: "{{ os_env }}"
    - debug:  msg="{{out}}"