--- 
- name: Pre-req
  hosts: controller
  remote_user: "jibin"
  become: true # needs become true for retrieving secrets otherwise" unable to get local issuer certificate "
  tasks:
    - include_vars:  dir=vars 

    - name: Fail if vault_token not set
      fail: msg="This play requires vault_token use --extra  --extra-vars 'vault_token=<token>'" 
      when: vault_token is not defined 
    - name: Retrieving secrets  from vault
      uri:
        url: "{{vault_addr}}{{item}}"
        method: GET
        headers:
          X-Vault-Token: "{{vault_token}}"

      with_items:
        - /v1/kv/openstack-deploy/MYSQL_PASS  
        - /v1/kv/openstack-deploy/GLANCE_DBPASS  
        - /v1/kv/openstack-deploy/GLANCE_PASS 
        - /v1/kv/openstack-deploy/KEYSTONE_ADMIN_PASS 
      register: output

    - name: Set MYSQL_PASS, GLANCE_DBPASS, GLANCE_PASS, KEYSTONE_ADMIN_PASS 
      set_fact: 
        MYSQL_PASS: "{{output.results[0].json.data.value}}" 
        GLANCE_DBPASS:   "{{output.results[1].json.data.value}}" 
        GLANCE_PASS:   "{{output.results[2].json.data.value}}" 
        KEYSTONE_ADMIN_PASS: "{{output.results[3].json.data.value}}"    

- name:  Setup mysql pre-req for glance system (identity)
  hosts: controller
  remote_user: "jibin"
  become: true 
  tasks: 
 
    
    
    - name: Create a new database with name 'glance'
      mysql_db:
        name: glance
        login_user: root 
        login_password: "{{MYSQL_PASS}}"
        login_unix_socket: /var/run/mysqld/mysqld.sock 
        state: present

      
 

    - name: Create glance user with password, grant on glance database
      mysql_user:
        state: present
        name: glance
        password: "{{GLANCE_DBPASS}}"
        login_unix_socket: /var/run/mysqld/mysqld.sock 
        login_user: root
        login_password: "{{MYSQL_PASS}}"
        host: "{{item}}"
        priv:  
          "glance.*:ALL,GRANT" 
      with_items:
        - localhost
        - '%'
      no_log: true 

# using https://docs.ansible.com/ansible/2.10/collections/openstack/cloud/endpoint_module.html
- name: Create glance user and it project
  hosts: controller
  remote_user: "jibin"
  become: true 
 
  vars:
    os_env:
      OS_USERNAME: admin
      OS_PASSWORD: "{{KEYSTONE_ADMIN_PASS}}"
      OS_PROJECT_NAME: admin
      OS_USER_DOMAIN_NAME: Default
      OS_PROJECT_DOMAIN_NAME: Default
      OS_AUTH_URL: http://controller:5000/v3
      OS_IDENTITY_API_VERSION: 3

  tasks:
    - name: Create glance user 
      os_user:
        state: present
        name: glance
        password: "{{GLANCE_PASS}}" 
        domain: default 
      environment: "{{ os_env }}"
    - name: assign glance admin role 
      os_user_role: 
        user: glance
        role: admin
        project: service
      environment: "{{ os_env }}"
    - name: Create service entity for glance  
      os_keystone_service: 
        state: present
        name: glance
        service_type: image
        description: OpenStack Image Service
      environment: "{{ os_env }}"

    - name: Create a PUBLIC service endpoint for glance
      openstack.cloud.endpoint: 
        service: glance
        endpoint_interface: public
        url: http://controller:9292
        region: RegionOne
        state: present
      environment: "{{ os_env }}"

    - name: Create an INTERNAL service endpoint for glance
      openstack.cloud.endpoint: 
        service: glance
        endpoint_interface: internal
        url: http://controller:9292
        region: RegionOne
        state: present
      environment: "{{ os_env }}"

    - name: Create an ADMIN service endpoint for glance
      openstack.cloud.endpoint: 
        service: glance
        endpoint_interface: admin
        url: http://controller:9292
        region: RegionOne
        state: present
      environment: "{{ os_env }}"


- name: Install and configure glance components 
  hosts: controller
  remote_user: "jibin"
  become: true 
  tasks: 
    - name: Install glance
      apt:
        name:  glance
        state: present 

    - name: Configure database, keystone (identity), pastedeploy, and glance store for glance
      template:
        src: "{{ playbook_dir }}/configs/templates/glance.ini.j2"
        dest: "/etc/glance/glance-api.conf"
        mode: '0640'
    - name: Create system user "glance"  and glance group
      user:
        name: glance 
        groups: glance 
        system: yes
    - name: Populate the Image service database
      shell: 'su -s /bin/sh -c "glance-manage db_sync" glance'
    - name: Restart glance-api 
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: glance-api

