
--- 
- name: Pre-req
  hosts: controller
  remote_user: "jibin"
  become: true # needs become true for retrieving secrets otherwise" unable to get local issuer certificate "
  tasks:
    - include_vars:  dir=vars 

    - name: Fail if vault_token not set
      fail: msg="This play requires vault_token use --extra  --extra-vars 'vault_token=<token>'" 
      when: vault_token is not defined 
    - name: Retrieving secrets  from vault
      uri:
        url: "{{vault_addr}}{{item}}"
        method: GET
        headers:
          X-Vault-Token: "{{vault_token}}"

      with_items:
        - /v1/kv/openstack-deploy/KEYSTONE_ADMIN_PASS  
      register: output

    - name: Set  KEYSTONE_ADMIN_PASS
      set_fact:  
        KEYSTONE_ADMIN_PASS:   "{{output.results[0].json.data.value}}" 

- name:  Create flavours and default networks
  hosts: controller
  remote_user: "jibin"
  become: true 

  vars:
    os_env:
      OS_USERNAME: admin
      OS_PASSWORD: "{{KEYSTONE_ADMIN_PASS}}"
      OS_PROJECT_NAME: admin
      OS_USER_DOMAIN_NAME: Default
      OS_PROJECT_DOMAIN_NAME: Default
      OS_AUTH_URL: http://controller:5000/v3
      OS_IDENTITY_API_VERSION: 3

  tasks: 
    - name: "Create 'tiny' flavor with 1024MB of RAM, 1 virtual CPU, and 10GB of local disk, and 10GB of ephemeral."
      openstack.cloud.compute_flavor: 
        state: present
        name: tiny
        ram: 1024
        vcpus: 1
        disk: 10
        ephemeral: 10
      environment: "{{ os_env }}"

    - name: "Create 'small' flavor with 2048 MB of RAM, 1 virtual CPU, and 20 GB of local disk"
      openstack.cloud.compute_flavor: 
        state: present
        name: small
        ram: 2048
        vcpus: 1
        disk: 20 
      environment: "{{ os_env }}"

    - name: "Create 'medium' flavor with 4096 MB of RAM, 2 virtual CPU, and 40 GB of local disk"
      openstack.cloud.compute_flavor: 
        state: present
        name: medium
        ram: 4096
        vcpus: 2
        disk: 40 
      environment: "{{ os_env }}"

    - name: "Create 'medium2' flavor with 4096 MB of RAM, 2 virtual CPU, and 100 GB of local disk"
      openstack.cloud.compute_flavor: 
        state: present
        name: medium2
        ram: 4096
        vcpus: 2
        disk: 100 
      environment: "{{ os_env }}"

    - name: "Create 'large' flavor with 8192 MB of RAM, 2 virtual CPU, and 40 GB of local disk"
      openstack.cloud.compute_flavor: 
        state: present
        name: large
        ram: 4096
        vcpus: 4
        disk: 80 
      environment: "{{ os_env }}"


    - name: "Create ext_network"

      openstack.cloud.network: 
        state: present
        name: ext_network
        external: true
      environment: "{{ os_env }}"

    - name: "Create network1"

      openstack.cloud.network: 
        state: present
        name: network1 
      environment: "{{ os_env }}"
      
    - name: "Create  net1subnet on network1"  
      openstack.cloud.subnet:
        state: present
        network_name: network1
        name: net1subnet
        cidr: 10.1.0.0/24
        dns_nameservers:
          - 8.8.8.7
          - 8.8.8.8
      environment: "{{ os_env }}"