--- 
- name:  Get passwords
  hosts: compute,controller
  remote_user: "jibin" 

  become: true # needs become true for retrieving secrets otherwise" unable to get local issuer certificate "
  tasks:
    - include_vars:  dir=vars 

    - name: Fail if vault_token not set
      fail: msg="This play requires vault_token use --extra  --extra-vars 'vault_token=<token>'" 
      when: vault_token is not defined 
    - name: Retrieving secrets  from vault
      uri:
        url: "{{vault_addr}}{{item}}"
        method: GET
        headers:
          X-Vault-Token: "{{vault_token}}"

      with_items: 
        - /v1/kv/openstack-deploy/NOVA_PASS  
        - /v1/kv/openstack-deploy/RABBIT_PASS 
        - /v1/kv/openstack-deploy/PLACEMENT_PASS
        - /v1/kv/openstack-deploy/METADATA_SECRET
        - /v1/kv/openstack-deploy/NEUTRON_PASS

      register: output

    - name: Set ppasswords as facts 
      set_fact:  
        NOVA_PASS:   "{{output.results[0].json.data.value}}"   
        RABBIT_PASS: "{{output.results[1].json.data.value}}"   
        PLACEMENT_PASS: "{{output.results[2].json.data.value}}"   
        METADATA_SECRET: "{{output.results[3].json.data.value}}"   
        NEUTRON_PASS: "{{output.results[4].json.data.value}}"   
 
- name: Install and configure nova compute components 
  hosts: compute
  remote_user: "jibin"
  become: true 
  tasks: 
    - name: Install nova packages
      apt:
        name: 
          - nova-compute
        state: present 
      

    - name: Configure   /etc/nova/nova.conf
      template:
        src: "{{ playbook_dir }}/configs/templates/nova_compute-{{inventory_hostname}}.conf.j2"
        dest: "/etc/nova/nova.conf"
        owner:  nova 
        mode: '0640'

    - name: Restart the Compute services
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: "{{item}}"
      with_items:
        - nova-compute
 