
- name: Pre-req
  hosts: compute
  remote_user: "jibin"
  become: true # needs become true for retrieving secrets otherwise" unable to get local issuer certificate "
  tasks:
    - include_vars:  dir=vars 

    - name: Fail if vault_token not set
      fail: msg="This play requires vault_token use --extra  --extra-vars 'vault_token=<token>'" 
      when: vault_token is not defined 
    - name: Retrieving secrets  from vault
      uri:
        url: "{{vault_addr}}{{item}}"
        method: GET
        headers:
          X-Vault-Token: "{{vault_token}}"

      with_items:
        - /v1/kv/openstack-deploy/NEUTRON_DBPASS  
        - /v1/kv/openstack-deploy/NEUTRON_PASS 
        - /v1/kv/openstack-deploy/RABBIT_PASS 
        - /v1/kv/openstack-deploy/NOVA_PASS 
      register: output

    - name: Set MYSQL_PASS, NEUTRON_DBPASS, NEUTRON_PASS, RABBIT_PASS 
      set_fact:  
        NEUTRON_DBPASS:   "{{output.results[0].json.data.value}}" 
        NEUTRON_PASS:   "{{output.results[1].json.data.value}}" 
        RABBIT_PASS: "{{output.results[2].json.data.value}}"    
        NOVA_PASS: "{{output.results[3].json.data.value}}"   

####  Networking Option 2: Self-service networks

- name: Install and configure compute node
  hosts: compute
  remote_user: "jibin"
  become: true 
  tasks: 
    - name: Install the components
      apt:
        name: 
          - neutron-linuxbridge-agent
        state: present 

    - name: Configure the server component on   /etc/neutron/neutron.conf
      template:
        src: "{{ playbook_dir }}/configs/templates/neutron_compute.conf.j2"
        dest: "/etc/neutron/neutron.conf"
        
        mode: '0640'     
    #https://docs.openstack.org/neutron/victoria/install/compute-install-option2-ubuntu.html#configure-the-linux-bridge-agent
    - name: Networking Option 2 Self-service networks - Configure the Linux bridge agent
      copy:
        src: "{{ playbook_dir }}/configs/linuxbridge_agent_{{inventory_hostname}}.ini"
        dest: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini"
        
        mode: '0640'


        
- name: Finalize installation

  hosts: compute
  remote_user: "jibin"
  become: true 
  tasks:  
    - name: Restart the nova-compute  and neutron-linuxbridge-agent service
      systemd:
        state: restarted
        enabled: yes
        daemon_reload: yes
        name: "{{item}}"
      with_items:
        - nova-compute 
        - neutron-linuxbridge-agent
 